## NumPy demo

This is a quick demo of some of the NumPy features that will be useful in CSC411.

Importing the modules we'll be using:

In [1]:
import numpy as np

NumPy uses the `array` data structure. The `array` data structure is an N-dimensional matrix of elements why are all of the same type.

In [2]:
a = np.array([5, 4, 10]) 

In [3]:
a

array([ 5,  4, 10])

We can access individual elements of the array:

In [4]:
a[0]

5

In [5]:
a[1:3]

array([ 4, 10])

Here is how to make a 2D array:

In [6]:
a = np.array([[4,5,6], [1,2,3]])

In [7]:
a

array([[4, 5, 6],
       [1, 2, 3]])

We can access elements of the 2D array like this:

In [8]:
a[1, 0]

1

We can slices matrices like this:

In [9]:
a[:, 1]  #Get the second column

array([5, 2])

In [10]:
a[:, 1].shape

(2,)

In [11]:
a[1, :].shape

(3,)

In [12]:
a[:, 1:2]  #Get the second column

array([[5],
       [2]])

In [13]:
a[:, :1].shape

(2, 1)

In [14]:
a[:, 1:3].shape

(2, 2)

We can get the shape of the array using

In [15]:
a.shape

(2, 3)

In [16]:
# transpose:
a.T

array([[4, 1],
       [5, 2],
       [6, 3]])

In [17]:
a * a

array([[16, 25, 36],
       [ 1,  4,  9]])

In [18]:
a + 1

array([[5, 6, 7],
       [2, 3, 4]])

In [19]:
f = lambda x: x * 3 + 2

In [20]:
f(a)

array([[14, 17, 20],
       [ 5,  8, 11]])

In [21]:
np.matmul(a.T, a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])